### ISSUE TITLE
Add state for initial readiness to play?

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#1032]
### Can your answer be found elsewhere?

- [x] I have searched existing [issues](https://github.com/SRGSSR/pillarbox-apple/issues?q=is%3Aissue+label%3Aquestion+) and found no similar question.

- [x] I have browsed the available documentation and found no answer to my question.

### Detailed question

From @NicolasBrunnerSRF:

> Question regarding `Player.playbackState` incoming!
> 
> We are currently building our new VideoFeed. Every VideoItem in the Feed can now have its own PlayerInstance thanks to Pillarbox. It works great :partying_face:
> 
> There is an autoplay feature where we automatically detect which video is in the “center” of the screen and start playing it. Other videos that have not yet started playing should display a TeaserImage (which does not correspond to the first frame of the video). Achieving this seems complicated to us:
> 
> - When setting the `player.items` (only one in our case), the player state will change from `.idle` to `.paused`
> - We rely on the player state to decide wether we will show the TeaserImage on top of the player. However we don’t want to use `.paused`, since when the user pauses the video after some time, we don’t want to show the TeaserImage.
> - This means we need to keep some News App internal state “.ready” or “playerIsReadyButHasNotYetStartedPlaying”.
> 
> Is there another/better way of doing this?

**Comment by defagos** [comment]
After discussion with @waliid this is definitely a UI behavior, not an intrinsic player state. So your approach is indeed correct since the application knows how it needs to behave in this case.

There are different ways of achieving this result. @walid might attach some sample code to this issue later on.

**Comment by waliid** [comment]
As @defagos said and what you have previously suggested is the best approach in my humble opinion. Relying on the `playbackState` and having an internal flag can be enough.

As @defagos mentioned, and as you previously suggested, this is the best approach in my humble opinion. Relying on the `playbackState` and having an internal flag should be enough.

Here is my view model code suggestion:

```swift
class ViewModel: ObservableObject {
    let player: Player
    @Published var hasPlaybackStarted: Bool = false

    init(urn: String) {
        player = Player(item: .urn(urn))
        player.propertiesPublisher.slice(at: \.playbackState)
            .compactMap { playbackState in
                switch playbackState {
                case .playing:
                    return true
                case .ended:
                    return false
                default:
                    return nil
                }
            }
            .assign(to: &$hasPlaybackStarted)
    }
}
```

**Comment by waliid** [comment]
As @defagos mentioned, and as you previously suggested, this is the best approach in my humble opinion. Relying on the `playbackState` and having an internal flag should be enough.

Here is my view model code suggestion:

```swift
class ViewModel: ObservableObject {
    let player: Player
    @Published var hasPlaybackStarted: Bool = false

    init(urn: String) {
        player = Player(item: .urn(urn))
        player.propertiesPublisher.slice(at: \.playbackState)
            .compactMap { playbackState in
                switch playbackState {
                case .playing:
                    return true
                case .ended:
                    return false
                default:
                    return nil
                }
            }
            .assign(to: &$hasPlaybackStarted)
    }
}
```

**Comment by NicolasBrunnerSRF** [comment]
Jep, that looks like our current implementation 👍

**Comment by defagos** [comment]
Great, will therefore close this issue (please reopen if you think that there is still something to discuss).
