### ISSUE TITLE
Improve developer onboarding

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#140]
**As a developer** I need documentation to help me setup the project correctly.

# Acceptance criteria

- I can build and run the demo on my machine.
- I can execute the unit tests on my machine.

# Tasks

- [x] List missing information and fix.

**Comment by defagos** [comment]
Missing: Ruby >= 2.7.0 is required.

**Comment by Waliid** [comment]
By running the project with an Intel processor, the command `bundle install` generate a new line on the `Gemfile.lock`.
