### ISSUE TITLE
Nightly 224 tests

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#222]
To be tested for example:

- Test playback of various contents offered in the demo.
- Playlist management.
- Control center integration.
- AirPlay.
- Error reporting.
- Behavior with poor network conditions.

Not implemented yet:

- End of playback behavior (when the last item has been played entirely).
- User interface (e.g. automatic control toggling).

Remark:

- Only URN-based medias have associated artworks.

**Comment by svenduvoisin** [comment]
Tests performed using Pillarbox Ntly 204 on Apple TV – some observations :
- Play/Pause icon in shrink format (middle of the screen).
- no dismiss of the control button.
- no timeline visible, no scrubber (not possible to seek).
- play/pause button on remote works only for pausing.
- Showcase stories : player format is zoomed.
- Playlist : impossible to choose manually.
- at the end of a playlist, the arrow "->" is transformed in a white button.

**Comment by svenduvoisin** [comment]
Tests performed using Pillarbox Ntly 222 on iPhone/iPad - some observations :
- dismiss controls (not hiding automatically).
- once played (at the end) play button visible but not active.
- Airplay icon in blue (should be blue when active...).
- random button (playlist) only mix the list (already told to Sam).
- no controls available (forward/backward, full screen, ...)
-

**Comment by svenduvoisin** [comment]
Tests performed using Pillarbox Ntly 224 on iPhone, casting via Airplay to an Apple TV 4K : some observations :

- C3 Live DVR / SRF DVR : position of the scrubber on the seekbar is not fully at the right side, when playing live.
- RSI Live : scrubber position and behavior when I go live on the iPhone.
- spinning wheel very little on iPhone (while casting).
- Stories : bottom bullets on Apple TV : small but OK, not a big difference between the current and the others, jiggling/virbrate.
- Playlist : controls dismiss after 5 seconds; too long comparing to content ?
- error messages (Token) don't show on TV when casting (only on iPhone).
- when paused, seeking do not show (seek bar & scrubber) on TV.

**Comment by defagos** [comment]
Thanks for the tests. Some answers:

> Tests performed using Pillarbox Ntly 204 on Apple TV – some observations :
> - Play/Pause icon in shrink format (middle of the screen).
> - no dismiss of the control button.
> - no timeline visible, no scrubber (not possible to seek).
> play/pause button on remote works only for pausing.

No tvOS view layout has been implemented. We will use the default tvOS in the end anyway.

> Showcase stories : player format is zoomed.
> Playlist : impossible to choose manually.
> at the end of a playlist, the arrow "->" is transformed in a white button.

The tvOS demos have received no dedicated attention yet.

> Tests performed using Pillarbox Ntly 222 on iPhone/iPad - some observations :
> dismiss controls (not hiding automatically).

We have only implemented a basic user interface. Gestures or timers to automatically hide controls are still missing.

> once played (at the end) play button visible but not active.

That is something we need to discuss and implement, see #173.

> Airplay icon in blue (should be blue when active...).

Improved in later nightlies.

> random button (playlist) only mix the list (already told to Sam).

Yes, this is not a shuffle as in audio apps, rather a randomize button to reorder the current playlist randomly.

> no controls available (forward/backward, full screen, ...)

Not implemented yet.

> C3 Live DVR / SRF DVR : position of the scrubber on the seekbar is not fully at the right side, when playing live.

Should be the case.

> RSI Live : scrubber position and behavior when I go live on the iPhone.

The stream is incorrectly seen as supporting DVR because of a packaging bug. Hopefully RSI will follow RTS and SRF and deliver only DVR livestreams in the future so that no ugly mitigation work is required from us, see #147.

> spinning wheel very little on iPhone (while casting).

No work has been done on UI usability yet.

> - Stories : bottom bullets on Apple TV : small but OK, not a big difference between the current and the others, jiggling/virbrate.
> - when paused, seeking do not show (seek bar & scrubber) on TV.
> - Playlist : controls dismiss after 5 seconds; too long comparing to content ?

No special work has been made for tvOS demo layouts.

> error messages (Token) don't show on TV when casting (only on iPhone).

**Comment by defagos** [comment]
@svenduvoisin I provided answers to what you found. I also linked to existing issues where appropriate. Thanks for your tests.
