### ISSUE TITLE
Improve CI stability

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#266]
**As a developer** I need a reliable CI to have a streamlined workflow. Currently some specific tests might fail.

# Acceptance criteria

- CI pass reliably on the CI.

# Tasks

- [x] Use CI test logs to identify tests that regularly fail.
- [x] Adjust them to improve stability (e.g. longer timeouts).

**Comment by defagos** [comment]
Flaky tests:

- `PlayerItemDurationPublisherTests.testDuration`
- ...

**Comment by waliid** [comment]
By updating the `URLSession` configuration from .default to .ephemeral, we considerably improve the stability of our tests but the result is not perfect! 
Moreover, I think it would be wiser to avoid network calls!

**Comment by defagos** [comment]
I agree, there is indeed a task to use only local test data, see #110.

**Comment by defagos** [comment]
Similar issues are reported for [slow CI agents](https://github.com/Quick/Nimble/issues/346). We should try to increase the default timeout and see whether tests pass more reliably on our agents.

**Comment by defagos** [comment]
Builds are still quite unreliable, I reopen this issue.

**Comment by defagos** [comment]
The measures applied in the associated PR were not sufficient. The PR #307 was difficult to check so remaining tolerances were adjusted. Tests should now hopefully be stable.
