### ISSUE TITLE
Add server selection to demo

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#281]
**As a developer or tester** I want to be able to use a different environment to browser content in the demo.

# Acceptance criteria

- Server selection is possible in the demo.

# Tasks

- [x] Add server selection combo in navigation.
- [x] Persist and restore choice if it makes sense.

**Comment by waliid** [comment]
Here is an example of how we can implement the view side :

```swift
struct ListsView: View {
    var body: some View {
        NavigationStack {
            ...
        }
        .navigationTitle("Lists")
        .toolbarTitleMenu {
            Button("test1") {}
            Button("test2") {}
            Button("test3") {}
        }
    }
```

**Comment by defagos** [comment]
This API seems available for tvOS as well but we should likely check its result first.

**Comment by waliid** [comment]
The API is effectively available but does nothing at first glance! Or I don't use it very well.
