### ISSUE TITLE
Handle blocked stream intervals

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#324]
**As an editor** I want forbidden content not to be playable if declared as such.

# Acceptance criteria

- Content intervals which have been declared as blocked cannot be played or seeked into.

# Tasks

- [ ] Discuss strategies with the team:
    - Long-term: Remove forbidden sections at the source. We could namely discuss whether streams should be re-encoded to eliminate undesired intervals so that players do not have to implement anything silly to avoid them, and so that even if streams are downloaded they do not contain the forbidden intervals anymore.
    - Short-term: What do we need to go to production? Do we need to support all use cases? Could we maybe display an error when part of the content is not playable instead?
- [ ] Implement discussed strategy (TBD).

**Comment by defagos** [comment]
Current recommendation:

- Document that stream packaging must remove blocked content entirely so that it cannot be downloaded.
- Until then we could simply return a resource loading error when a blocked segment is detected. Unpublished content is likely old in general so doing a lot of work so that people can watch old news content is superfluous anyway.

**Comment by Chuysalgafo** [comment]
> **As an editor** I want forbidden content not to be playable if declared as such.
> 
> # Acceptance criteria
> 
> - Content intervals which have been declared as blocked cannot be played or seeked into.
> 
> # Tasks
> 
> - [ ] Discuss strategies with the team:
>     - Long-term: Remove forbidden sections at the source. We could namely discuss whether streams should be re-encoded to eliminate undesired intervals so that players do not have to implement anything silly to avoid them, and so that even if streams are downloaded they do not contain the forbidden intervals anymore.
>     - Short-term: What do we need to go to production? Do we need to support all use cases? Could we maybe display an error when part of the content is not playable instead?
> - [ ] Implement discussed strategy (TBD).

**Comment by defagos** [comment]
This has been implemented in #851.
