### ISSUE TITLE
Incorrect analytics

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#412]
### Description of the problem

Manual inspection revealed the following issues with our current implementation;

1. There is no `SRG` vendor constant available but this constant is required for Play Suisse.
2. The `playrt` comScore event is sent too often, e.g. when pausing the player. This should not be the case.
3. When switching to another playlist item by tapping on it in the playlist demo, the `play` event for the new item often lacks metadata.

### Reproducibility

Always

#### Issue 1

No need to reproduce.

#### Issue 2

1. Play some demo URN content while inspecting network with a proxy tool.
2. Pause playback and observe that an undesired `playrt` comScore event is sent.

#### Issue 3

1. Open the URN playlist demo while inspecting network with a proxy tool.
2. Tap on another item of the playlist and observe the emitted `play` event. This event often lacks metadata.

### Library version

0.4.0

### Operating system

iOS 16

### Is there an existing issue for this?

- [X] I have searched existing issues and found no similar bug report.

**Comment by waliid** [comment]
_`CurrentTracker.swift - line 16, 17`_
```swift
configureTrackingPublisher(player: player)
configureAssetPublisher(for: item)
```

Regarding the third point, inverted these two instructions seem to do the trick!
