### ISSUE TITLE
Reintroduce PhaseAnimator

### ISSUE THREAD

**Issue by waliid** [SRGSSR/pillarbox-apple#490]
**As a Pillarbox developer**, I would like to reintroduce `PhaseAnimator`. Indeed, the `PhaseAnimator` usage has been [removed](https://github.com/SRGSSR/pillarbox-apple/pull/488) because it was causing some UI freeze.

# Acceptance criteria

- The UI should not freeze anymore when the `isBusy` modifier is used.

# Tasks

- [x] Revert the [commit](https://github.com/SRGSSR/pillarbox-apple/commit/b44e8c068699053a541e1c803393df42ca673ed7).
- [x] Test the behavior.

**Comment by defagos** [comment]
Beta 4 fixes this issue.

**Comment by defagos** [comment]
Still not fixed in beta 5.

**Comment by defagos** [comment]
Still not fixed in beta 6.

**Comment by defagos** [comment]
Still not fixed in beta 7.

**Comment by defagos** [comment]
Still not fixed in RC. The hang seems related to the fact we are adding or removing the animation based on the `isBusy` flag. If we remove this condition there is no hang anymore, but the player is leaked when dismissing the view, so there is likely another issue with phase animators.

**Comment by defagos** [comment]
Also see this [post](https://developer.apple.com/forums/thread/737912) on the developer forums.
