### ISSUE TITLE
Video fails to play

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#606]
### Description of the problem

The video `urn:rts:video:14378203` does not play (note that this content has limited availability) when French subtitles are enabled. A cryptic error is returned by the player

```
Error Domain=CoreMediaErrorDomain Code=-16012 "(null)"
```

### Reproducibility

Always

### Steps to reproduce

1. Play the provided URN with the Pillarbox demo.
2. Playback either fails immediately if French subtitles were already set. If playback starts simply enable these subtitles to make playback immediately fail.

The issue affects Letterbox as well, both on iOS as well as on the web in Safari.

### Library version

0.7.0

### Operating system

iOS 17

### Is there an existing issue for this?

- [X] I have searched existing issues and found no similar bug report.

**Comment by defagos** [comment]
# Analysis

This content is protected by DRM but we can still check its [master playlist](https://rtsvod-euwe.akamaized.net/c246a547-e900-4087-9361-a23175086666/RTSVOD-cbec8579-16d6.ism/manifest(format=m3u8-aapl,encryption=cbcs-aapl)):

```
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="fr",NAME="text_fra_sdh",DEFAULT=NO,AUTOSELECT=YES,FORCED=NO,URI="https://rtsvod-euwe.akamaized.net:443/f928a3d4-f2ac-4a98-804b-f6e55239550f/4ce78d2b27d770d825c58766336e2df9/grans_20231015_full_fra_sdh.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="audio_fra",LANGUAGE="fr",URI="QualityLevels(128000)/Manifest(audio_fra,format=m3u8-aapl)"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="audio_eng",LANGUAGE="en",DEFAULT=YES,URI="QualityLevels(128000)/Manifest(audio_eng,format=m3u8-aapl)"
#EXT-X-STREAM-INF:SUBTITLES="subs",CLOSED-CAPTIONS=NONE,BANDWIDTH=658242,RESOLUTION=484x272,CODECS="avc1.4d401f,mp4a.40.2",AUDIO="audio"
QualityLevels(500104)/Manifest(video,format=m3u8-aapl)
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=658242,RESOLUTION=484x272,CODECS="avc1.4d401f",URI="QualityLevels(500104)/Manifest(video,format=m3u8-aapl,type=keyframes)"
#EXT-X-STREAM-INF:SUBTITLES="subs",CLOSED-CAPTIONS=NONE,BANDWIDTH=1373738,RESOLUTION=640x360,CODECS="avc1.4d401f,mp4a.40.2",AUDIO="audio"
QualityLevels(1200198)/Manifest(video,format=m3u8-aapl)
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=1373738,RESOLUTION=640x360,CODECS="avc1.4d401f",URI="QualityLevels(1200198)/Manifest(video,format=m3u8-aapl,type=keyframes)"
#EXT-X-STREAM-INF:SUBTITLES="subs",CLOSED-CAPTIONS=NONE,BANDWIDTH=2191502,RESOLUTION=960x540,CODECS="avc1.4d401f,mp4a.40.2",AUDIO="audio"
QualityLevels(2000359)/Manifest(video,format=m3u8-aapl)
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=2191502,RESOLUTION=960x540,CODECS="avc1.4d401f",URI="QualityLevels(2000359)/Manifest(video,format=m3u8-aapl,type=keyframes)"
#EXT-X-STREAM-INF:SUBTITLES="subs",CLOSED-CAPTIONS=NONE,BANDWIDTH=3724695,RESOLUTION=1280x720,CODECS="avc1.4d401f,mp4a.40.2",AUDIO="audio"
QualityLevels(3500547)/Manifest(video,format=m3u8-aapl)
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=3724695,RESOLUTION=1280x720,CODECS="avc1.4d401f",URI="QualityLevels(3500547)/Manifest(video,format=m3u8-aapl,type=keyframes)"
#EXT-X-STREAM-INF:SUBTITLES="subs",CLOSED-CAPTIONS=NONE,BANDWIDTH=6280315,RESOLUTION=1920x1080,CODECS="avc1.640029,mp4a.40.2",AUDIO="audio"
QualityLevels(6001154)/Manifest(video,format=m3u8-aapl)
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=6280315,RESOLUTION=1920x1080,CODECS="avc1.640029",URI="QualityLevels(6001154)/Manifest(video,format=m3u8-aapl,type=keyframes)"
```

as well as the French subtitles media playlist:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:10
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:10.000000,
grans_20231015_full_fra_sdh/seg-00000.vtt
#EXTINF:10.000000,
grans_20231015_full_fra_sdh/seg-00001.vtt
#EXTINF:10.000000,
grans_20231015_full_fra_sdh/seg-00002.vtt
#EXTINF:10.000000,
grans_20231015_full_fra_sdh/seg-00003.vtt
#EXTINF:10.000000,
...
grans_20231015_full_fra_sdh/seg-00241.vtt
#EXTINF:10.000000,
grans_20231015_full_fra_sdh/seg-00242.vtt
#EXT-X-ENDLIST
```

Attempting to validate the subtitles playlist we get an error:

```
mediastreamvalidator -V https://rtsvod-euwe.akamaized.net/f928a3d4-f2ac-4a98-804b-f6e55239550f/4ce78d2b27d770d825c58766336e2df9/grans_20231015_full_fra_sdh.m3u8
mediastreamvalidator: mediastreamvalidator: Version 1.12 (541.12-211008)

Validate https://rtsvod-euwe.akamaized.net/f928a3d4-f2ac-4a98-804b-f6e55239550f/4ce78d2b27d770d825c58766336e2df9/grans_20231015_full_fra_sdh.m3u8, fetch http
[/f928a3d4-f2ac-4a98-804b-f6e55239550f/4ce78d2b27d770d825c58766336e2df9/grans_20231015_full_fra_sdh.m3u8] Started root playlist download
[/f928a3d4-f2ac-4a98-804b-f6e55239550f/4ce78d2b27d770d825c58766336e2df9/grans_20231015_full_fra_sdh.m3u8] Started media playlist download
[/f928a3d4-f2ac-4a98-804b-f6e55239550f/4ce78d2b27d770d825c58766336e2df9/grans_20231015_full_fra_sdh.m3u8] Received media playlist response
[/f928a3d4-f2ac-4a98-804b-f6e55239550f/4ce78d2b27d770d825c58766336e2df9/grans_20231015_full_fra_sdh.m3u8] SequenceNum: 0  Size: 110 bytes Duration: 10.0000 sec Bitrate: 11.0000
Error injecting segment data
Error injecting segment data
[/f928a3d4-f2ac-4a98-804b-f6e55239550f/4ce78d2b27d770d825c58766336e2df9/grans_20231015_full_fra_sdh.m3u8] SequenceNum: 1  Size: 49 bytes Duration: 10.0000 sec Bitrate: 4.9000
[/f928a3d4-f2ac-4a98-804b-f6e55239550f/4ce78d2b27d770d825c58766336e2df9/grans_20231015_full_fra_sdh.m3u8] SequenceNum: 2  Size: 96 bytes Duration: 10.0000 sec Bitrate: 9.6000
...
```

There is something obviously wrong with the first chunk. Having a look at it:

```
WEBVTT

1
00:00.000 --> 00:00.000


2
00:00.200 --> 00:02.360
"STOP!"
(UPSAHL)

3
00:02.560 --> 00:25.880
---
```

we can observe that there is an entry with a length of 0, which does not pass [validation](https://w3c.github.io/webvtt.js/parser.html).

If we intercept the 1st subtitle chunk request with Charles proxy and fix this issue playback works fine.

# Fix

The stream is invalid and needs to be delivered again. Maybe the error is in the source and not in the encoding process.

@bgaudaen Could we have a look at the source subtitles?

# Workaround

In the meantime users encountering this issue should open another content which plays fine (e.g. another episode of the same series), open the subtitles panel to explicitly disable subtitles, then open the content which was not correctly playing before. Playback will start but of course these users cannot have French subtitles until the stream is fixed.

@svenduvoisin You can provide the above workaround to our users in the meantime.

**Comment by defagos** [comment]
I wanted to post the following reply to an [existing thread](https://developer.apple.com/forums/thread/730530?login=true#reply-to-this-question):

> We recently got the same problem. In our case this revealed an issue with subtitles. One of the VTT segments contained a cue with zero length (identical start and end times), leading to playback failing. Fixing this issue made the content play fine again.

But sadly attempting to post a reply currently fails.

**Comment by amtins** [comment]
@defagos, @waliid I opened the following issue [SMAC-481884](https://jira.srg.beecollaboration.com/browse/SMAC-481884).

**Comment by defagos** [comment]
For some reason having _cue_ in the text was preventing the comment from being posted.
