### ISSUE TITLE
Play an mp4 with a WebVTT subtitle file

### ISSUE THREAD

**Issue by swilliams-intellum** [SRGSSR/pillarbox-apple#729]
### Detailed question

I need to play MP4s with subtitles in a WebVVT file. I am aware that it would be better to consume a M3U8, but that isn't an option for me. 

Is there a way to add the WebVTT to the player without using an M3U8, and if so, can you point me in the right direction?

### Can your answer be found elsewhere?

- [X] I have searched existing [issues](https://github.com/SRGSSR/pillarbox-apple/issues?q=is%3Aissue+label%3Aquestion+) and found no similar question.

- [X] I have browsed the available documentation and found no answer to my question.

**Comment by defagos** [comment]
Hi,

The player cannot be supplied subtitles externally but you can embed WebVTT subtitles into your MP4 as [soft subtitles](https://www.baeldung.com/linux/subtitles-ffmpeg):

```
ffmpeg -i input.mp4 -i subtitles.webvtt -c copy -c:s mov_text -metadata:s:s:0 language=eng output.mp4
```

Hope that helps.

**Comment by swilliams-intellum** [comment]
Unfortunately, not, but thanks for the tip anyway. I was hoping for something like the HTML video track tag.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track
