### ISSUE TITLE
Update Apple developer tests

### ISSUE THREAD

**Issue by amtins** [SRGSSR/pillarbox-apple#748]
**As an SRG SSR Apple developer** I need to enhance the suite of exercises provided to job applicants.

## Acceptance criteria

- More exercises are available if meaningful.

# Tasks

- [x] Discuss with the Play team.
- [x] ~Add exercises with various lengths (and solutions) to our exercise and solution repositories.~

**Comment by defagos** [comment]
Discussed with the Play team. They did not need our help to write new exercises AFAWK.
