### ISSUE TITLE
Display metadata in the iOS system player

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#818]
**As a Pillarbox demo user** I want to know what is being played when nothing else on screen is telling me. **As a developer integrating Pillarbox** I want the system UI to be integrated with Pillarbox player as tightly as possible without additional effort.

# Acceptance criteria

- The system player UI displays all possible information it can handle.

# Hints

Maybe the article for the [companion tvOS experience](https://developer.apple.com/documentation/avkit/customizing_the_tvos_playback_experience) can be helpful, or maybe there is a similar documentation for the iOS system UI.

# Tasks

- [ ] List which information might be missing on the system UI.
- [ ] Add it.

**Comment by waliid** [comment]
We have learned that the key `.iTunesMetadataContentRating` seems only working on `tvOS` to constraint content related to age restriction (see also: https://developer.apple.com/wwdc19/503).
