### ISSUE TITLE
Stability issues when using a USB-C / USB-C cable to connect to an external screen with debug builds

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#846]
### Description of the problem

When connecting to an external screen with a USB-C / USB-C cable the following stability issues are observed in debug builds:

- The display flickers.
- A crash might happen when closing the player.

Setup:

- iPad Pro M1, 17.5 beta 3 / iPhone 15 Pro, 17.4
- Screen: HP Z34c G3
- Cable: Super Speed USB 3.1

### Remark

The issue does not arise when using a lightning to HDMI connector on older devices. It also does not arise in release builds, only in debug builds.

Older setup:

- iPhone 14 Pro, 17.4
- Screen: HP Z34c G3
- Cable: High Speed HDMI
- Adapter: Lightning to HDMI from Apple, A1438

### Reproducibility

Always

### Steps to reproduce

Use the first setup above to reproduce the issue.

### Library version

1.0.1

### Operating system

17.4

### Is there an existing issue for this?

- [X] I have searched existing issues and found no similar bug report.

**Comment by defagos** [comment]
Since this affects debug builds only an investigation or fix is likely not a priority (or even needed), but we should likely document this behavior as a known issue.

**Comment by defagos** [comment]
We identified an issue with Lightning to HDMI adapters and iOS 17.4. DRM-protected content fails to play.

The issue is fixed in 17.5 beta 3. Though the issue reported here is not related to DRM or such kind of connector I suspect both problems might somehow be related to the same regression. I am therefore quite optimistic that 17.5 will fix the present issue as well.

**Comment by defagos** [comment]
No issue with our iPad Air running 17.2 with a USB-C / USB-C cable. Our iPad Pro running 17.5 is affected, though. Seems like a regression we will need to report.

**Comment by waliid** [comment]
> No issue with our iPad Air running 17.2 with a USB-C / USB-C cable. Our iPad Pro running 17.5 is affected, though. Seems like a regression we will need to report.

Here is the video captures : 

| iPad Air - iOS 17.2 | iPad Pro - iOS 17.5 Beta 3 |
|--------|--------|
| <video src="https://github.com/SRGSSR/pillarbox-apple/assets/3347810/801df6ae-a6d2-4075-b220-43ed77aa855d"/> | <video src="https://github.com/SRGSSR/pillarbox-apple/assets/3347810/925999fc-43ec-46ef-81e1-e599946029e7"/> |

**Comment by waliid** [comment]
Issue reported to Apple.
