### ISSUE TITLE
VideoItem/AudioItem startDate

### ISSUE THREAD

**Issue by NicolasBrunnerSRF** [SRGSSR/pillarbox-apple#917]
**Hold On - still writing this...**

### Is there an existing similar feature request?

- [X] I have searched existing [features](https://github.com/SRGSSR/pillarbox-apple/issues?q=is%3Aissue+label%3Aenhancement+) and found no similar request.

- [X] I have browsed the available API and found no way to achieve the use case I described.

### Use case description

**As a developer integrating Pillarbox** I would like to know when a livestream `VideoItem` and/or `AudioItem` is going to start.

Background: We would like to create a CountdownView for livestreams that are not available yet.
![Livestreams](https://github.com/SRGSSR/pillarbox-apple/assets/98830687/b23a0458-890e-48e6-b807-4c5ee68c17af)

### Acceptance criteria

- VideoItem and AudioItem have a new property `public let startDate: Date` containing the date 
`

**Comment by defagos** [comment]
As discussed with @NicolasBrunnerSRF who closed this issue, SRF apps already have the info. I still added a backlog entry for us to improve the demo and show how we can integrate a countdown or availability date.
